In [30]:
import pandas as pd
import numpy as np

df = pd.read_csv("database.csv", low_memory=False)

df.head()

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
0,000001,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,January,1.0,Murder or Manslaughter,...,Unknown,Male,15,Native American/Alaska Native,Unknown,Acquaintance,Blunt Object,0.0,0.0,FBI
1,000002,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,March,1.0,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0.0,0.0,FBI
2,000003,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,March,2.0,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0.0,0.0,FBI
3,000004,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,April,1.0,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0.0,0.0,FBI
4,000005,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980.0,April,2.0,Murder or Manslaughter,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0.0,1.0,FBI

In [31]:
print(df.shape)
print(df.columns)

(638455, 24)
Index(['Record ID', 'Agency Code', 'Agency Name', 'Agency Type', 'City',
       'State', 'Year', 'Month', 'Incident', 'Crime Type', 'Crime Solved',
       'Victim Sex', 'Victim Age', 'Victim Race', 'Victim Ethnicity',
       'Perpetrator Sex', 'Perpetrator Age', 'Perpetrator Race',
       'Perpetrator Ethnicity', 'Relationship', 'Weapon', 'Victim Count',
       'Perpetrator Count', 'Record Source'],
      dtype='str')

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 638455 entries, 0 to 638454
Data columns (total 24 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Record ID              638455 non-null  str
 1   Agency Code            638454 non-null  str
 2   Agency Name            638454 non-null  str
 3   Agency Type            638454 non-null  str
 4   City                   638454 non-null  str
 5   State                  638454 non-null  str
 6   Year                   638454 non-null  float64
 7   Month                  638454 non-null  str
 8   Incident               638454 non-null  float64
 9   Crime Type             638454 non-null  str
 10  Crime Solved           638454 non-null  str
 11  Victim Sex             638454 non-null  str
 12  Victim Age             638454 non-null  float64
 13  Victim Race            638454 non-null  str
 14  Victim Ethnicity       638454 non-null  str
 15  Perpetrator Sex        638454 non-null  str
 16  Perpetrator Age        638454 non-null  str
 17  Perpetrator Race       638454 non-null  str
 18  Perpetrator Ethnicity  638454 non-null  str
 19  Relationship           638454 non-null  str
 20  Weapon                 638454 non-null  str
 21  Victim Count           638454 non-null  float64
 22  Perpetrator Count      638454 non-null  float64
 23  Record Source          638454 non-null  str
dtypes: float64(5), str(19)
memory usage: 116.9 MB

In [33]:
df.describe(include='all')

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
count,638455,638454,638454,638454,638454,638454,638454.000000,638454,638454.000000,638454,...,638454,638454,638454,638454,638454,638454,638454,638454.000000,638454.000000,638454
unique,638455,12003,9216,7,1782,51,NaN,12,NaN,2,...,3,3,101,5,3,28,16,NaN,NaN,2
top,000001,NY03030,New York,Municipal Police,Los Angeles,California,NaN,July,NaN,Murder or Manslaughter,...,Unknown,Male,0,White,Unknown,Unknown,Handgun,NaN,NaN,FBI
freq,1,38416,38416,493026,44511,99783,NaN,58696,NaN,629338,...,368303,399541,216327,218243,446410,273013,317484,NaN,NaN,616647
mean,NaN,NaN,NaN,NaN,NaN,NaN,1995.801102,NaN,22.967924,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.123334,0.185224,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,9.927693,NaN,92.149821,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.537733,0.585496,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,1980.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,1987.000000,NaN,1.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,1995.000000,NaN,2.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,2004.000000,NaN,10.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,2014.000000,NaN,999.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,10.000000,NaN

In [34]:
df.isnull().sum().sort_values(ascending=False)

Agency Code              1
Agency Name              1
Agency Type              1
City                     1
Year                     1
State                    1
Month                    1
Incident                 1
Perpetrator Age          1
Crime Type               1
Crime Solved             1
Victim Sex               1
Victim Age               1
Victim Race              1
Victim Ethnicity         1
Perpetrator Sex          1
Weapon                   1
Perpetrator Race         1
Perpetrator Ethnicity    1
Relationship             1
Perpetrator Count        1
Victim Count             1
Record Source            1
Record ID                0
dtype: int64

In [35]:
df.duplicated().sum()

np.int64(0)

In [36]:
df['State'].unique()

<StringArray>
[              'Alaska',              'Alabama',             'Arkansas',
              'Arizona',           'California',             'Colorado',
          'Connecticut', 'District of Columbia',             'Delaware',
              'Florida',              'Georgia',               'Hawaii',
                 'Iowa',                'Idaho',             'Illinois',
              'Indiana',               'Kansas',             'Kentucky',
            'Louisiana',        'Massachusetts',             'Maryland',
                'Maine',             'Michigan',            'Minnesota',
             'Missouri',          'Mississippi',              'Montana',
             'Nebraska',       'North Carolina',         'North Dakota',
        'New Hampshire',           'New Jersey',           'New Mexico',
               'Nevada',             'New York',                 'Ohio',
             'Oklahoma',               'Oregon',         'Pennsylvania',
        'Rhodes Island',       'South Carolina',         'South Dakota',
            'Tennessee',                'Texas',                 'Utah',
             'Virginia',              'Vermont',           'Washington',
            'Wisconsin',        'West Virginia',              'Wyoming',
                    nan]
Length: 52, dtype: str

In [37]:
df['Weapon'].unique()

<StringArray>
[ 'Blunt Object', 'Strangulation',       'Unknown',         'Rifle',
         'Knife',       'Firearm',       'Shotgun',          'Fall',
       'Handgun',      'Drowning',   'Suffocation',    'Explosives',
          'Fire',         'Drugs',           'Gun',        'Poison',
             nan]
Length: 17, dtype: str

In [38]:
df['Relationship'].unique()

<StringArray>
[        'Acquaintance',              'Unknown',                 'Wife',
             'Stranger',           'Girlfriend',           'Ex-Husband',
              'Brother',         'Stepdaughter',              'Husband',
               'Sister',               'Friend',               'Family',
             'Neighbor',               'Father',               'In-Law',
                  'Son',              'Ex-Wife',            'Boyfriend',
               'Mother',   'Common-Law Husband',      'Common-Law Wife',
           'Stepfather',              'Stepson',           'Stepmother',
             'Daughter', 'Boyfriend/Girlfriend',             'Employer',
             'Employee',                    nan]
Length: 29, dtype: str